import { Dimensions } from "react-native";

export const Constants = {
  default_theme: "light",
  default_language: "it",
  api_url: process.env.EXPO_PUBLIC_API_URL,
  images: {
    defaultProfile: require("@/assets/icon.png"),
  },
  totalWidth: Dimensions.get("screen").width,
  totalHeight: Dimensions.get("screen").height,
  defaultNumPlaceholders: 2,
  errorMessage: "Errori nel caricamento dell'utente",
  maxVote: 30,
  minVote: 18,
  maxVoteDegree: 110,
  minVoteDegree: 66,
  messages: [
    "Lasciati guidare dall'ispirazione, non dalla paura. Sei destinato a brillare.",
    "Non c'è errore nel tentativo. Solo l'opportunità di imparare e crescere.",
    "Abbraccia il cambiamento. È l'unica costante nella vita.",
    "Osa sognare in grande. Il mondo è il tuo palcoscenico.",
    "Il successo è il risultato di azioni coraggiose e decisioni sagge.",
    "Le migliori idee iniziano come sogni. Ora è il momento di realizzarle.",
    "Non aspettare il momento perfetto. Inizia adesso e adatta lungo il cammino.",
    "Sii audace. Sii audace. Sii te stesso.",
    "Il segreto del progresso è iniziare. Prendi il primo passo oggi stesso.",
    "Nessun obiettivo è troppo grande se dividi il percorso in piccoli passi.",
    "Fallo. O non farlo. Non c'è tentativo.",
    "Non lasciare che la paura ti impedisca di raggiungere le stelle.",
    "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.",
    "L'unica cosa che è sicura di fallire è non provare affatto.",
    "Le tue azioni parlano più forte delle tue parole. Fai accadere le cose.",
    "Non c'è limite a ciò che puoi realizzare se credi in te stesso.",
    "Sii il capitano della tua nave. Dirigila verso nuovi orizzonti.",
    "L'unico modo per predire il futuro è crearlo.",
    "Lascia che la tua passione guidi le tue azioni. Il resto seguirà.",
    "La tua determinazione è la chiave per sbloccare ogni porta.",
    "Sii instancabile nel perseguire i tuoi sogni. La perseveranza paga sempre.",
    "Ogni passo avanti è un passo più vicino al tuo obiettivo. Continua a camminare.",
    "Non limitarti a sognare. Fai di quei sogni una realtà tangibile.",
    "L'unico ostacolo che conta sei tu stesso. Superalo.",
    "Non permettere agli altri di definire il tuo valore. Dimostraglielo.",
    "La vita è troppo breve per vivere secondo le aspettative degli altri. Vivi la tua verità.",
    "La tua vita è il risultato delle tue scelte. Scegli con saggezza.",
    "Non lasciare che il timore del fallimento ti impedisca di tentare. Sii coraggioso.",
    "La strada per il successo è piena di ostacoli. Sii determinato a superarli.",
    "Sii il regista della tua vita. Scrivi il tuo copione.",
    "Non c'è momento migliore per iniziare che adesso. Il futuro appartiene a coloro che agiscono.",
    "La tua potenzialità è illimitata. Scoprila e nutrila.",
    "Sii resiliente. Le tue cadute ti rendono più forte.",
    "Le tue azioni oggi plasmano il tuo domani. Fai ogni mossa contare.",
    "Abbraccia il processo. È parte del viaggio verso il successo.",
    "Niente è impossibile quando ti dedichi con tutto il cuore.",
    "Non permettere alle paure del passato di limitare il tuo futuro.",
    "I tuoi sogni sono il carburante che alimenta il motore della tua vita.",
    "La tua determinazione è la tua arma segreta. Usa con saggezza.",
    "Nessuno può fermarti se decidi di continuare a muoverti in avanti.",
    "I tuoi sogni possono diventare realtà se sei disposto a lavorare per loro.",
    "Non c'è limite a ciò che puoi raggiungere quando ti sforzi al massimo.",
    "La tua volontà è il tuo più grande alleato. Sfruttalo al massimo.",
    "Ogni sfida è un'opportunità mascherata. Affrontala con fiducia.",
    "Sii l'architetto della tua vita. Costruisci il tuo destino.",
    "Non lasciare che il rumore del mondo soffochi la tua voce interiore.",
    "Le tue azioni parlano più forte delle tue parole. Dimostra chi sei veramente.",
    "Non permettere agli ostacoli di diventare scuse. Trova un modo, crea una strada.",
    "Sii il pioniere del tuo destino. Esplora nuove strade senza paura.",
    "La vita è un'opportunità, coglila con entusiasmo e determinazione.",
  ],
};
